import Link from "next/link";
import { ContactForm } from "./contact-form";
import { ActivityChart } from "./activity-chart";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

const plans = [
  { name: "Starter", price: "Rp 500.000", units: "2 mesin", color: "bg-[#ffd60a]", features: ["Hingga 500 sesi/bulan", "Analitik usaha", "Kustomisasi layar kiosk"] },
  { name: "Growth", price: "Rp 1.200.000", units: "5 mesin", color: "bg-[#22d3ee]", features: ["Kuota sesi sesuai paket", "Pantau beberapa lokasi", "Kelola voucher"] },
  { name: "Enterprise", price: "Diskusikan", units: "Kebutuhan khusus", color: "bg-[#f472b6]", features: ["Penyesuaian jumlah mesin", "Ruang lingkup berdasarkan kebutuhan", "Hubungi tim SnapArcade"] },
];

const features = [
  { name: "Analitik", title: "Baca usaha dari satu tempat.", text: "Lihat ringkasan pendapatan, sesi foto, dan status mesin dalam dashboard pemilik.", color: "bg-[#ffd60a]", mark: "01" },
  { name: "Hardware", title: "Kamera dan printer, satu alur.", text: "Kiosk dirancang untuk terhubung dengan kamera DSLR atau mirrorless dan printer foto melalui USB. Dukungan bergantung pada perangkat dan browser.", color: "bg-[#22d3ee]", mark: "02" },
  { name: "Kustomisasi", title: "Sesuaikan booth untuk tiap acara.", text: "Atur warna, logo, teks sambutan, dan frame dari pengaturan kiosk, tanpa mengubah kode aplikasi.", color: "bg-[#a3e635]", mark: "03" },
];

function Eyebrow({ children }: { children: React.ReactNode }) {
  return <p className="mb-4 font-bold uppercase tracking-[0.12em]">{children}</p>;
}

function Title({ eyebrow, title, intro }: { eyebrow: string; title: string; intro: string }) {
  return <header className="mb-12 max-w-3xl"><Eyebrow>{eyebrow}</Eyebrow><h1 className="font-[family-name:var(--font-space-grotesk)] text-5xl font-extrabold leading-[1.02] sm:text-7xl">{title}</h1><p className="mt-6 text-lg leading-8">{intro}</p></header>;
}

export function HomePage() {
  return <main>
    <section className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-16 sm:py-24 md:grid-cols-[1.08fr_0.92fr]">
      <div><Eyebrow>Platform operasional photobooth</Eyebrow><h1 className="max-w-3xl font-[family-name:var(--font-space-grotesk)] text-6xl font-extrabold leading-[0.98] sm:text-8xl">Semua booth. <span className="text-[#b45309]">Satu kendali.</span></h1><p className="mt-7 max-w-xl text-lg leading-8">Pantau mesin, sesi, pembayaran, dan tampilan kiosk dari satu dashboard. Biar kamu fokus bikin acara jadi lebih seru.</p><div className="mt-8 flex flex-wrap gap-4"><Link className="nb-button min-h-12" href="/kontak">Hubungi tim kami</Link><Link className="inline-flex min-h-12 items-center font-bold underline underline-offset-4" href="/fitur">Lihat cara kerjanya</Link></div><p className="mt-5 text-sm font-semibold">Pendaftaran owner saat ini melalui undangan. <Link className="underline underline-offset-4" href="/masuk">Sudah punya akun? Login</Link></p></div>
      <div className="relative mx-auto w-full max-w-xl rotate-1"><Card aria-label="Ilustrasi konseptual ringkasan dashboard dan kiosk SnapArcade" className="rounded-xl border-[3px] border-black bg-[#ffd60a] p-5 shadow-[4px_4px_0_0_#0a0a0a] sm:p-7"><div className="flex items-center justify-between border-b-[3px] border-black pb-4"><span className="font-[family-name:var(--font-space-grotesk)] text-xl font-extrabold">SnapArcade / Ringkasan</span><span className="border-2 border-black bg-white px-3 py-1 text-xs font-bold">PRATINJAU</span></div><div className="mt-5 grid grid-cols-2 gap-4"><div className="nb-card bg-white p-4"><p className="text-sm font-bold">Aktivitas sesi</p><div aria-hidden="true" className="mt-4 h-10 border-[3px] border-black bg-[#22d3ee]" /><p className="mt-3 text-sm">Contoh tampilan</p></div><div className="nb-card bg-[#f472b6] p-4"><p className="text-sm font-bold">Status mesin</p><div aria-hidden="true" className="mt-4 h-10 border-[3px] border-black bg-[#a3e635]" /><p className="mt-3 text-sm">Data ilustrasi</p></div></div><div className="nb-card mt-4 bg-white p-4"><div className="flex items-center justify-between"><p className="font-bold">Aktivitas booth</p><span className="text-sm">Ringkasan ilustrasi</span></div><div className="mt-4"><ActivityChart /></div></div></Card><span aria-hidden="true" className="absolute -bottom-5 -right-3 -rotate-3 border-[3px] border-black bg-[#a3e635] px-4 py-2 font-[family-name:var(--font-space-grotesk)] text-lg font-extrabold shadow-[4px_4px_0_0_#0a0a0a]">Dibuat untuk booth kamu</span></div>
    </section>
    <section className="border-y-[3px] border-black bg-white px-5 py-16 sm:py-20"><div className="mx-auto max-w-7xl"><Eyebrow>Dari setup sampai hasil foto</Eyebrow><div className="grid gap-10 md:grid-cols-[0.8fr_1.2fr]"><h2 className="font-[family-name:var(--font-space-grotesk)] text-4xl font-extrabold sm:text-5xl">Operasional lebih tertata, pengalaman foto tetap menyenangkan.</h2><div className="grid gap-5">{features.map((feature) => <article className="grid gap-4 border-t-[3px] border-black py-5 sm:grid-cols-[90px_1fr]" key={feature.name}><div className={`nb-card grid min-h-20 place-items-center ${feature.color} font-[family-name:var(--font-archivo-black)] text-2xl`}>{feature.mark}</div><div><p className="font-bold">{feature.name}</p><h3 className="mt-1 font-[family-name:var(--font-space-grotesk)] text-2xl font-extrabold">{feature.title}</h3><p className="mt-2 leading-7">{feature.text}</p></div></article>)}</div></div><Link className="mt-8 inline-flex min-h-11 items-center font-bold underline underline-offset-4" href="/fitur">Kenali fitur SnapArcade</Link></div></section>
    <Pricing compact />
      <section className="border-y-[3px] border-black bg-[#22d3ee] px-5 py-14"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-6"><div><Eyebrow>Belum ada pendaftaran mandiri</Eyebrow><h2 className="font-[family-name:var(--font-space-grotesk)] text-4xl font-extrabold">Bawa detail booth ke satu percakapan.</h2><p className="mt-2">Tim kami membantu memetakan perangkat, paket, dan akses undangan.</p></div><Button nativeButton={false} render={<Link href="/kontak" />} variant="public">Mulai percakapan</Button></div></section>
  </main>;
}

export function FeaturesPage() {
  return <main className="mx-auto max-w-7xl px-5 py-16 sm:py-24"><Title eyebrow="Fitur SnapArcade" title="Kendali booth, dari satu tempat." intro="Rangkaian alat untuk memantau usaha photobooth, menyiapkan kiosk, dan merapikan alur sesi foto."/><div className="space-y-6">{features.map((feature, i) => <article className={`grid gap-7 border-[3px] border-black p-6 shadow-[4px_4px_0_0_#0a0a0a] sm:p-9 md:grid-cols-[0.7fr_1.3fr] ${feature.color}`} key={feature.name}><div className="font-[family-name:var(--font-archivo-black)] text-6xl">{feature.mark}</div><div><p className="font-bold">{feature.name}</p><h2 className="mt-2 font-[family-name:var(--font-space-grotesk)] text-3xl font-extrabold sm:text-4xl">{feature.title}</h2><p className="mt-4 max-w-2xl leading-7">{feature.text}</p></div></article>)}</div><section className="mt-20 border-t-[3px] border-black pt-10"><Eyebrow>Alur kiosk</Eyebrow><h2 className="max-w-2xl font-[family-name:var(--font-space-grotesk)] text-4xl font-extrabold">Dari sentuhan pertama sampai foto dibawa pulang.</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{["Pilih paket sesi", "Bayar atau pakai voucher", "Ambil dan pilih foto", "Cetak atau unduh"].map((step, i) => <div className="border-t-[3px] border-black py-4" key={step}><span className="font-[family-name:var(--font-archivo-black)] text-3xl">0{i + 1}</span><p className="mt-3 font-bold">{step}</p></div>)}</div></section></main>;
}

function Pricing({ compact = false }: { compact?: boolean }) {
  return <section className="mx-auto max-w-7xl px-5 py-16 sm:py-24"><div className="mb-10 flex flex-wrap items-end justify-between gap-5"><div><Eyebrow>Paket langganan</Eyebrow><h2 className="font-[family-name:var(--font-space-grotesk)] text-4xl font-extrabold sm:text-5xl">Pilih skala yang pas.</h2><p className="mt-3">Harga contoh sesuai data paket PRD, konfirmasi detail melalui tim SnapArcade.</p></div>{compact && <Link className="min-h-11 inline-flex items-center font-bold underline underline-offset-4" href="/harga">Lihat rincian paket</Link>}</div><div className="grid gap-6 md:grid-cols-2">{plans.slice(0, 2).map((plan) => <article className={`nb-card flex flex-col p-6 ${plan.color}`} key={plan.name}><p className="font-bold">{plan.name}</p><p className="mt-5 font-[family-name:var(--font-archivo-black)] text-3xl">{plan.price}</p><p className="mt-1 font-bold">{`${plan.units} / bulan`}</p><ul className="my-7 flex-1 space-y-3 border-t-2 border-black pt-5">{plan.features.map((item) => <li className="flex gap-3" key={item}><span aria-hidden="true" className="font-extrabold">+</span>{item}</li>)}</ul><Link className="nb-button bg-white" href="/kontak">Tanyakan paket {plan.name}</Link></article>)}<article className={`nb-card flex flex-col p-6 md:col-span-2 ${plans[2].color}`}><div className="grid gap-6 md:grid-cols-[0.7fr_1.3fr] md:items-center"><div><p className="font-bold">{plans[2].name}</p><p className="mt-5 font-[family-name:var(--font-archivo-black)] text-3xl">{plans[2].price}</p><p className="mt-1 font-bold">{plans[2].units}</p></div><div><ul className="space-y-3 border-t-2 border-black pt-5 md:border-t-0 md:border-l-2 md:pl-6 md:pt-0">{plans[2].features.map((item) => <li className="flex gap-3" key={item}><span aria-hidden="true" className="font-extrabold">+</span>{item}</li>)}</ul><Link className="nb-button mt-6 bg-white" href="/kontak">Tanyakan paket {plans[2].name}</Link></div></div></article></div><p className="mt-6 max-w-3xl text-sm leading-6">Paket Starter dan Growth menggunakan harga contoh dari PRD. Kuota sesi Growth, add-on sesi, dan ketentuan final perlu dikonfirmasi sebelum berlangganan.</p></section>;
}

export function PricingPage() { return <main><div className="mx-auto max-w-7xl px-5 pt-16 sm:pt-24"><Title eyebrow="Harga" title="Mulai dari kebutuhan booth kamu." intro="Paket contoh untuk skala usaha berbeda. Pendaftaran dilakukan melalui undangan, hubungi tim untuk membahas kecocokan paket."/></div><Pricing/><section className="mx-auto max-w-7xl px-5 pb-20"><div className="nb-card bg-[#a3e635] p-6 sm:p-8"><h2 className="font-[family-name:var(--font-space-grotesk)] text-3xl font-extrabold">Butuh tambahan sesi?</h2><p className="mt-3 max-w-2xl leading-7">PRD mencantumkan pembelian add-on sesi melalui dashboard. Harga dan kuota add-on belum ditetapkan di data paket publik, jadi hubungi tim untuk detail terkini.</p><Link className="nb-button mt-6 bg-white" href="/kontak">Tanyakan add-on sesi</Link></div></section></main>; }

export function AboutPage() { return <main className="mx-auto max-w-7xl px-5 py-16 sm:py-24"><Title eyebrow="Tentang SnapArcade" title="Bikin booth lebih mudah dikelola." intro="SnapArcade berangkat dari kebutuhan operator photobooth yang ingin mengelola mesin, pembayaran, dan pengalaman pelanggan tanpa berpindah-pindah alat."/><section className="grid gap-6 md:grid-cols-2"><article className="nb-card bg-[#ffd60a] p-7"><Eyebrow>Tantangan yang kami lihat</Eyebrow><h2 className="font-[family-name:var(--font-space-grotesk)] text-3xl font-extrabold">Banyak booth, banyak hal yang harus dipantau.</h2><p className="mt-4 leading-7">Status mesin, sesi foto, pembayaran, voucher, hingga koneksi perangkat sering tersebar dalam alur kerja berbeda.</p></article><article className="nb-card bg-[#22d3ee] p-7"><Eyebrow>Arah yang kami tuju</Eyebrow><h2 className="font-[family-name:var(--font-space-grotesk)] text-3xl font-extrabold">Satu alur untuk pemilik dan pelanggan.</h2><p className="mt-4 leading-7">Kami ingin membantu pemilik merapikan operasional sambil menjaga pengalaman kiosk yang sederhana dan menyenangkan.</p></article></section><p className="mt-10 max-w-3xl border-l-[6px] border-black pl-5 text-lg leading-8">SnapArcade masih dikembangkan. Informasi tentang tim dan kisah produk akan ditambahkan setelah tersedia untuk dibagikan.</p></main>; }

export function ContactPage() { return <main className="mx-auto grid max-w-7xl gap-12 px-5 py-16 sm:py-24 md:grid-cols-[0.9fr_1.1fr]"><div><Title eyebrow="Kontak" title="Ceritakan booth kamu." intro="Tanya soal paket, kebutuhan perangkat, atau akses undangan. Form ini demo dan belum mengirim data ke admin."/><div className="border-t-[3px] border-black pt-5"><p className="font-bold">Butuh bantuan melalui email?</p><a className="mt-2 inline-block min-h-11 font-bold underline underline-offset-4" href="mailto:support@snaparcade.id">support@snaparcade.id</a><p className="mt-2 text-sm leading-6">Alamat dukungan ini mengikuti contoh domain PRD. Pastikan inbox sudah aktif sebelum dipublikasikan.</p></div></div><ContactForm /></main>; }

const questions = [
  ["Bagaimana cara mendaftar sebagai owner?", "Pendaftaran owner tertutup. Akses akun diberikan melalui undangan Superadmin."],
  ["Paket apa yang tersedia?", "PRD mencantumkan Starter untuk 2 mesin dengan contoh harga Rp 500.000/bulan, Growth untuk 5 mesin dengan contoh harga Rp 1.200.000/bulan, serta Enterprise berdasarkan kebutuhan."],
  ["Payment gateway apa yang digunakan di kiosk?", "PRD merencanakan Midtrans, Xendit, atau Tripay dengan settlement langsung ke akun pemilik booth."],
  ["Apakah kamera dan printer saya bisa digunakan?", "Kiosk dirancang untuk kamera DSLR atau mirrorless dan printer USB. Kecocokan bergantung pada perangkat, driver, dan dukungan browser."],
  ["Apakah foto pelanggan disimpan?", "Rancangan PRD menyebut penyimpanan sementara untuk hasil sesi. Detail retensi dan kebijakan final perlu mengikuti implementasi yang aktif."],
];

export function FaqPage() { return <main className="mx-auto max-w-7xl px-5 py-16 sm:py-24"><Title eyebrow="FAQ" title="Yang sering ditanyakan." intro="Jawaban ringkas tentang akses, paket, perangkat, dan cara kerja SnapArcade."/><div className="max-w-4xl">{questions.map(([question, answer], i) => <details className="group border-t-[3px] border-black py-5" key={question}><summary className="flex min-h-11 cursor-pointer list-none items-center justify-between gap-5 font-[family-name:var(--font-space-grotesk)] text-xl font-bold">{question}<span aria-hidden="true" className="text-2xl group-open:rotate-45">+</span></summary><p className="max-w-3xl py-4 leading-7">{answer}</p></details>)}</div><p className="mt-8">Belum menemukan jawaban? <Link className="font-bold underline underline-offset-4" href="/kontak">Hubungi tim SnapArcade</Link>.</p></main>; }

const terms = [
  ["Akses layanan", "Akun owner dan staff diberikan melalui undangan. Pengguna bertanggung jawab menjaga akses akun dan menggunakan layanan sesuai peran yang diberikan."],
  ["Paket dan pembayaran", "Harga yang ditampilkan merupakan data contoh dalam PRD dan perlu dikonfirmasi. Rincian paket, tagihan, dan perubahan layanan mengikuti informasi yang disepakati saat layanan tersedia."],
  ["Perangkat pihak ketiga", "Koneksi kamera, printer, tablet, dan payment gateway bergantung pada kompatibilitas dan ketentuan penyedia masing-masing."],
  ["Status dokumen", "Dokumen ini merupakan ringkasan dummy untuk prototipe, bukan nasihat hukum atau syarat final yang mengikat."],
];

export function TermsPage() { return <LegalPage title="Syarat & Ketentuan" intro="Ringkasan ketentuan penggunaan SnapArcade untuk kebutuhan prototipe." sections={terms}/>; }

const privacy = [
  ["Informasi yang dapat diproses", "Rancangan layanan dapat memproses data akun, informasi operasional booth, transaksi, serta foto yang dibuat dalam sesi kiosk."],
  ["Tujuan penggunaan", "Data digunakan untuk autentikasi, operasional dashboard dan kiosk, pemrosesan pembayaran melalui penyedia terkait, serta dukungan layanan."],
  ["Penyimpanan dan akses", "PRD merancang penyimpanan foto sementara dengan masa retensi. Detail teknis, periode, dan kontrol akses harus mengikuti kebijakan implementasi sebelum layanan diluncurkan."],
  ["Status dokumen", "Ini adalah ringkasan dummy untuk prototipe dan bukan kebijakan privasi final. Jangan gunakan data pribadi nyata pada formulir demo."],
];

export function PrivacyPage() { return <LegalPage title="Kebijakan Privasi" intro="Gambaran awal tentang data yang berkaitan dengan penggunaan platform dan kiosk." sections={privacy}/>; }

function LegalPage({ title, intro, sections }: { title: string; intro: string; sections: string[][] }) { return <main className="mx-auto max-w-7xl px-5 py-16 sm:py-24"><Title eyebrow="Informasi" title={title} intro={intro}/><div className="max-w-4xl">{sections.map(([heading, text]) => <section className="border-t-[3px] border-black py-6" key={heading}><h2 className="font-[family-name:var(--font-space-grotesk)] text-2xl font-extrabold">{heading}</h2><p className="mt-3 leading-7">{text}</p></section>)}</div></main>; }
