"use client";

import { useState } from "react";
import { Printer } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { defaultPrinterSettings, type PrinterSettings } from "@/lib/printer-settings";
import { usePrinterUSB } from "@/lib/printer-usb";
import { saveKiosk } from "@/app/crud-actions";
import { toast } from "sonner";

export function PrinterPanel({ kioskId, currentSettings, canPersist = false, kiosk }: { kioskId: string; currentSettings: PrinterSettings | null; canPersist?: boolean; kiosk?: Record<string, unknown> }) {
  const [settings, setSettings] = useState<PrinterSettings>(currentSettings ?? defaultPrinterSettings); const [saving, setSaving] = useState(false); const printer = usePrinterUSB();
  const update = <K extends keyof PrinterSettings>(key: K, value: PrinterSettings[K]) => setSettings((current) => ({ ...current, [key]: value }));
  const report = async (result: "success" | "failed" | "cancelled") => { await fetch("/api/kiosk/printer/report", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kioskId, result, jobType: "test_print", elapsedMs: 0, progress: printer.progress, device: { product: printer.deviceLabel } }) }).catch(() => undefined); };
  const save = async () => { if (!kiosk) return; setSaving(true); const result = await saveKiosk(kioskId, { ...kiosk, printerSettings: settings }); setSaving(false); result.ok ? toast.success("Pengaturan printer disimpan.") : toast.error("Pengaturan printer gagal disimpan."); };
  const test = async () => { const connected = printer.state === "connected" || printer.state === "printing" || await printer.connect(); if (!connected) return; const result = await printer.print(new Uint8Array([83, 110, 97, 112, 65, 114, 99, 97, 100, 101]), settings); await report(result.result); result.ok ? toast.success("Test pattern dikirim ke printer.") : toast.error("Test print gagal atau dibatalkan."); };
  return <Card><CardHeader><CardTitle className="flex items-center gap-2"><Printer className="size-5" />Printer USB</CardTitle><CardDescription>Generic ESC/POS melalui WebUSB. DNP, Epson, Citizen belum didukung.</CardDescription></CardHeader><CardContent className="space-y-4"><p className="text-sm">{printer.supported ? printer.state === "connected" || printer.state === "printing" ? `Terhubung: ${printer.deviceLabel}` : "Belum terhubung" : "WebUSB tidak tersedia. Gunakan Chromium."}</p><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-2 text-sm">Kertas<Select value={settings.paperSize} onValueChange={(value) => update("paperSize", value as PrinterSettings["paperSize"])}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="4R">4R</SelectItem><SelectItem value="2x6">2x6</SelectItem><SelectItem value="5R">5R</SelectItem></SelectContent></Select></label><label className="grid gap-2 text-sm">Orientasi<Select value={settings.orientation} onValueChange={(value) => update("orientation", value as PrinterSettings["orientation"])}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="portrait">Portrait</SelectItem><SelectItem value="landscape">Landscape</SelectItem></SelectContent></Select></label><label className="grid gap-2 text-sm">DPI<Input type="number" min={180} max={600} value={settings.dpi} onChange={(event) => update("dpi", Number(event.target.value))} /></label><label className="grid gap-2 text-sm">Maks. copy<Input type="number" min={1} max={10} value={settings.maxCopy} onChange={(event) => update("maxCopy", Number(event.target.value))} /></label></div><p className="text-xs text-muted-foreground">{printer.error || (printer.state === "printing" ? `Mengirim ${printer.progress}%` : "Test pattern adalah pola diagnostik, bukan foto pelanggan.")}</p><div className="flex flex-wrap gap-2"><Button onClick={() => void printer.connect()} disabled={!printer.supported || printer.state === "requesting"}>Hubungkan</Button><Button variant="outline" onClick={() => void test()} disabled={!printer.supported || printer.state === "printing"}><Printer />Test print</Button>{printer.state === "printing" && <Button variant="outline" onClick={printer.cancel}>Batalkan</Button>}{canPersist && <Button variant="secondary" onClick={() => void save()} disabled={saving}>{saving ? "Menyimpan..." : "Simpan pengaturan"}</Button>}</div></CardContent></Card>;
}
